/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kontoverwaltungen;

import javax.swing.JOptionPane;

/**
 *
 * @author franz
 */
public class KontoGUI extends javax.swing.JFrame {

    private Konto k;
    
    public KontoGUI() {
        initComponents();
        liBenutzer.setModel(k);
        k = new Konto(lbMoney, taTransactions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        plCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liBenutzer = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTransactions = new javax.swing.JTextArea();
        plSouth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbMoney = new javax.swing.JLabel();

        jMenuItem1.setText("add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddBenutzer(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("test");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTesten(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(new java.awt.BorderLayout(2, 2));

        plCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Log"));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(120, 152));

        liBenutzer.setComponentPopupMenu(jPopupMenu1);
        liBenutzer.setPreferredSize(new java.awt.Dimension(100, 90));
        jScrollPane1.setViewportView(liBenutzer);

        plCenter.add(jScrollPane1, java.awt.BorderLayout.WEST);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Log-output"));

        taTransactions.setColumns(20);
        taTransactions.setRows(5);
        jScrollPane2.setViewportView(taTransactions);

        plCenter.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(plCenter, java.awt.BorderLayout.CENTER);

        plSouth.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Account"));
        plSouth.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(160, 16));
        plSouth.add(jLabel1, java.awt.BorderLayout.WEST);

        lbMoney.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMoney.setText("1000,00 Euro");
        plSouth.add(lbMoney, java.awt.BorderLayout.CENTER);

        getContentPane().add(plSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddBenutzer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddBenutzer
        String name = JOptionPane.showInputDialog(this, "Wie lautet der Name des neuen Benutzers?", "Eingabe benötigt", JOptionPane.QUESTION_MESSAGE);
        if (name != null) {
            if (!name.isEmpty()) {
                k.add(new KontoBenutzer(name));
            } else {
                JOptionPane.showMessageDialog(this, "Sie müssen einen Namen eingeben!", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_onAddBenutzer

    private void onTesten(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTesten
        
    }//GEN-LAST:event_onTesten

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMoney;
    private javax.swing.JList<String> liBenutzer;
    private javax.swing.JPanel plCenter;
    private javax.swing.JPanel plSouth;
    private javax.swing.JTextArea taTransactions;
    // End of variables declaration//GEN-END:variables
}
